services:

  hmi:
    image: nets/hmi-browser:1.0.0
    hostname: hmi
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
    environment:
      LAUNCH_URL: http://edge/hmi
      KIOSK: 1
      PERSISTENT: 1
      SHOW_CURSOR: 1
      WINDOW_SIZE: 1280,1024
    volumes:
      - hmi-volume:/data # Only required if using PERSISTENT flag (see below)
    restart: always

volumes:
  hmi-volume:
    external: true
